image: maven:latest
stages:
  - build
  - deploy

variables : 
    AWS_DEFAULT_REGION : "us-west-2"
    ZIP_NAME : "OpportunityHack-0.0.1-SNAPSHOT"

build:
    stage: build
    script:
         - cd Backend/OpportunityHack
         - mvn clean install -DskipTests

deploy:
    stage: deploy
    script:
        - apt-get -qq update && apt-get -qq install -y python
        - apt-get -qq update
        - apt-get -qq install -y python-pip
        - pip install awscli --ignore-installed six
        - time =`date`
        - mv $ZIP_NAME "$ZIP_NAME-$time.jar"
        - aws s3 cp "$ZIP_NAME.jar" "s3://elasticbeanstalk-us-west-2-631867123265/"
        - aws elasticbeanstalk create-application-version --application-name OpportunityHack --version-label "$ZIP_NAME-$time" --description "$ZIP_NAME-$time" --source-bundle S3Bucket="s3://elasticbeanstalk-us-west-2-631867123265/",S3Key="" --auto-create-application
        - aws elasticbeanstalk update-environment --application-name OpportunityHack --environment-name Opportunityhack-env  --version-label "$time"


